- pitch/models.py
- pitch/tests/test_models.py
- project1/settings.py
Tạo test cases cho các models Order, Comment, Voucher, Pitch, Image
> Create tests case for models

- .gitignore
- README.md
- pitch/urls.py
- pitch/views.py
- project1/urls.py
- static/css/navbar.css
- static/css/styles.css
- static/js/action_navbar.js
- templates/base_generic.html
- templates/index.html
- templates/navbar.html
- templates/pagination.html
- templates/registration/logged_out.html
- templates/registration/login.html
- templates/registration/password_change_done.html
- templates/registration/password_reset_complete.html
- templates/registration/password_reset_confirm.html
- templates/registration/password_reset_done.html
- templates/registration/password_reset_email.html
- templates/registration/password_reset_form.html
[Task #65313](https://edu-redmine.sun-asterisk.vn/issues/65313)
Tạo chức năng đăng nhập đăng xuất
> Login and Logout

- account/admin.py
- account/apps.py
- account/forms.py
- account/models.py
- account/tests.py
- account/urls.py
- account/views.py
- pitch/views.py
- project1/urls.py
- templates/navbar.html
- templates/registration/logged_out.html
- templates/registration/password_reset_confirm.html
- templates/registration/password_reset_done.html
- templates/registration/signup.html
- templates/select_language.html
[Task 65416](https://edu-redmine.sun-asterisk.vn/issues/65416)
> Create interface signup

- static/css/login.css
- static/css/styles.css
- templates/base_generic.html
- templates/registration/signup.html
> Giao diện trang đăng ký 

- account/views.py
- pitch/admin.py
- pitch/models.py
- pitch/urls.py
- pitch/views.py
- project1/settings.py
- project1/urls.py
- static/css/styles.css
- templates/email/verify_email_signup.html
- templates/navbar.html
- templates/pitch/order_list.html
[Task 65546](https://edu-redmine.sun-asterisk.vn/issues/65546)
Hiển thị danh sách các sân bóng đã đặt.
> List my ordered

- pitch/forms.py
- pitch/models.py
- pitch/urls.py
- pitch/views.py
- project1/urls.py
- static/css/styles.css
- templates/base_generic.html
- templates/email/notify_cancel_order.html
- templates/navbar.html
- templates/pitch/order_detail.html
- templates/pitch/order_list.html
- templates/registration/signup.html
[Task #65330](https://edu-redmine.sun-asterisk.vn/issues/65330)
Khi Order ở trạng thái vừa đặt và chưa được admin xác nhận thì người dùng có thể hủy lịch đặt sân bóng.
Hệ thống sẽ gửi email thông báo về thông tin sân bóng cho người dùng
> User cancel order

- static/css/pitch_details.css
- templates/base_generic.html
- templates/pitch/pitch_detail.html
[Task 65549](https://edu-redmine.sun-asterisk.vn/issues/65549)
> Pitch_detail interface

- pitch/forms.py
- pitch/models.py
- pitch/views.py
- static/css/send_email_success.css
- static/css/styles.css
- templates/base_generic.html
- templates/email/notify_cancel_order.html
- templates/email/notify_order_pitch.html
- templates/email/verify_email_signup.html
- templates/pagination.html
- templates/pitch/order_detail.html
- templates/registration/send_mail_success.html
- templates/registration/verify_email_fail.html
- templates/registration/verify_email_success.html
[Task #65442](https://edu-redmine.sun-asterisk.vn/issues/65442): View Verify Email thành công
[Task#65761](https://edu-redmine.sun-asterisk.vn/issues/65761): Tạo Template Email đặt lịch
[Task#65331](https://edu-redmine.sun-asterisk.vn/issues/65331): Tạo Template Email hủy lịch
> Create interface verify account

- pitch/forms.py
- pitch/urls.py
- pitch/views.py
- static/css/login.css
- static/css/search_bar.css
- static/css/styles.css
- templates/base_generic.html
- templates/navbar.html
- templates/pitch/pitch_card.html
- templates/pitch/pitch_search.html
- templates/pitch/search_bar.html
[Task 65310](https://edu-redmine.sun-asterisk.vn/issues/65310)
> Tạo chức năng tìm kiếm sân bóng

- pitch/admin.py
- templates/email/canceled_email.html
- templates/email/confirmed_email.html
Khi admin phê duyệt sẽ gửi mail cho ng dùng kết quả phê quyệt
[Task 65321](https://edu-redmine.sun-asterisk.vn/issues/65321)
> Approved-Canceled Order email

- pitch/forms.py
- pitch/views.py
- static/css/styles.css
- templates/pagination.html
- templates/pitch/pitch_search.html
[Task #66063](https://edu-redmine.sun-asterisk.vn/issues/66063)
Mô tả:
- Fix placeholder của input price và address
- Thêm full text search cho tìm kiếm theo từ khóa. 
- Thêm phân trang
> Fix bug search and add full text search by Title with description

- pitch/tests/test_forms.py
- pitch/tests/test_views.py
- pitch/urls.py
- pitch/views.py
- templates/pitch/pitch_comment.html
> Test view + form Comment

- pitch/admin.py
- pitch/forms.py
- requirements.txt
- static/css/custom_input.css
- templates/admin/custom_change_list.html
- templates/admin/custom_fieldset.html
[Task #66471](https://edu-redmine.sun-asterisk.vn/issues/66471)
Admin sẽ filter sân bóng, size, surface và theo một khoảng thời gian.
> Custom search admin site

- pitch/admin.py
- pitch/models.py
[Task #66446](https://edu-redmine.sun-asterisk.vn/issues/66446)
> Export list order

- README.md
- account/mail.py
- account/views.py
- log/README.md
- pitch/admin.py
- pitch/cron.py
- pitch/models.py
- pitch/views.py
- project1/settings.py
- requirements.txt
- templates/email/notify_cancel_order.html
- templates/email/sale_statistics.html
- templates/email/verify_email_signup.html
[Task #66448](https://edu-redmine.sun-asterisk.vn/issues/66448)
Gửi mail cho admin theo thời gian cố định
Chỉnh lại logger của hệ thống
Fix lỗi sửa email khi người dùng hủy đơn.
> Create Job send email schedule

- account/admin.py
- pitch/admin.py
- pitch/cron.py
- pitch/custom_fnc.py
- pitch/views.py
- project1/admin.py
- project1/apps.py
- project1/settings.py
- project1/urls.py
- requirements.txt
- static/css/styles.css
- templates/admin/index.html
- templates/admin/revenue_statistic.html
- templates/admin/statistical_table.html
- templates/email/sale_statistics.html
[Task #66472](https://edu-redmine.sun-asterisk.vn/issues/66472)
Thống kê doanh số tháng trước và tự động gửi mail vào ngày đầu tháng cho admin
> Revenue statistical

- pitch/factory.py
- pitch/management/commands/seed.py
- pitch/models.py
- pitch/tests/test_models.py
- pitch/tests/test_views.py
- pitch/views.py
- templates/base_generic.html
- templates/pitch/pitch_cmt.html
- templates/pitch/pitch_detail.html
> test comment form_view

- api/tests.py
- api/views.py
- pitch/tests/test_api.py
- project1/settings.py
1. Thêm xác thực bằng session_id
> API Login Testcase

- api/serialize.py
- api/urls.py
- api/views.py
[Task #66457](https://edu-redmine.sun-asterisk.vn/issues/66457)
Api yêu cầu quyền admin
Thống kê doanh thu theo sân, order bằng filter.
> Revenue Statistic

- api/serialize.py
- api/urls.py
- api/views.py
[Task #66459](https://edu-redmine.sun-asterisk.vn/issues/66459)
Thống kê tỷ lệ đặt sân theo các trường.
> Statistic order rate

- api/serialize.py
- api/urls.py
- api/views.py
- pitch/models.py
- project1/settings.py
1. Cho phép người dùng tạo reply đánh giá
2. Danh sách đánh giá được sắp xếp theo mới nhất
3. Cho phép xem danh sách theo n đánh  giá 
[Task 66458](https://edu-redmine.sun-asterisk.vn/issues/66458)
> API create and view replies

- api/serialize.py
- api/tests/test_apis.py
- api/views.py
[Task #66466](https://edu-redmine.sun-asterisk.vn/issues/66466)
> Test change info

- api/tests/test_apis.py
- api/views.py
[Task #66460](https://edu-redmine.sun-asterisk.vn/issues/66460)
> Order Rate Statistic Api Test
